In [58]:
import cv2
import numpy as np

In [112]:
im = cv2.imread('rr.jpg')

In [60]:
im.shape

(3378, 5200, 3)

In [80]:
l = np.load('l.npy')

In [62]:
len(l)

334

In [108]:
new = []
max_dist = 0
for i in range(len(l)):
    min1 = 3839690000000
    point=[0,0]
    loc=-1
    for j in range(len(l)):
        dist = (l[i][0]-l[j][0])**2+(l[i][1]-l[j][1])**2
        if dist==0:
            continue
        min1 = min(dist, min1)
        if min1==dist:
            point=l[j]
            loc=j
            
    new.append([point,loc])

In [74]:
def fun(val):
    return ((val[1]-point[1])**2+(val[0]-point[0])**2)

In [81]:
new2=[]

for i in range(len(l)):
    point=l[i]
    t=sorted(l, key=fun)
    new2.append(t[1:6])

In [66]:
new

[array([394, 314], dtype=int64),
 array([394, 316], dtype=int64),
 array([394, 314], dtype=int64),
 array([441, 594], dtype=int64),
 array([439, 596], dtype=int64),
 array([448, 594], dtype=int64),
 array([445, 594], dtype=int64),
 array([ 497, 5146], dtype=int64),
 array([ 497, 5144], dtype=int64),
 array([ 507, 4914], dtype=int64),
 array([ 506, 4913], dtype=int64),
 array([532, 963], dtype=int64),
 array([531, 964], dtype=int64),
 array([ 563, 1206], dtype=int64),
 array([ 562, 1205], dtype=int64),
 array([ 612, 3413], dtype=int64),
 array([ 608, 3401], dtype=int64),
 array([ 617, 2904], dtype=int64),
 array([ 618, 2902], dtype=int64),
 array([ 617, 2904], dtype=int64),
 array([ 622, 3452], dtype=int64),
 array([ 618, 2902], dtype=int64),
 array([ 619, 3448], dtype=int64),
 array([ 636, 2820], dtype=int64),
 array([ 636, 3508], dtype=int64),
 array([ 633, 2823], dtype=int64),
 array([ 633, 3501], dtype=int64),
 array([ 650, 2730], dtype=int64),
 array([ 652, 2730], dtype=int64),
 ar

In [93]:
for i in range(len(l)):
    start=(l[i][1], l[i][0])
    #end=(new[i][1], new[i][0])
    color=(0,0,0)
    thickness=2
    final_end =(-1,-1)
    min_diff=1000000000
    for j in range(5):
        end=(new2[i][j][1], new2[i][j][0])
        numerator=float(end[1]-start[1])
        denominator=float(end[0]-start[0])
        if denominator==0:
            curr_slope=1000000000
        else:
            curr_slope=numerator/denominator
        ratio = max(slope[i], curr_slope)/min(slope[i], curr_slope)
        if ratio<2:
            im=cv2.line(im, start, end, color, thickness)
            final_end=end
            break
            
        diff=abs(slope[i]-curr_slope)
        if diff<min_diff:
            min_diff=diff
            final_end=end
        
    im=cv2.line(im, start, final_end, color, thickness)

C:\Users\dsharma\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: RuntimeWarning: divide by zero encountered in double_scalars
  app.launch_new_instance()


In [119]:
for i in range(len(l)):
    start=(l[i][1], l[i][0])
    end=(new[i][0][1], new[i][0][0])
    color=(0,0,0)
    thickness=2
    
    numerator=float(end[1]-start[1])
    denominator=float(end[0]-start[0])
    if denominator==0:
        curr_slope=1000000000
    else:
        curr_slope=numerator/denominator
    ratio = max(slope[i], curr_slope)/max(min(slope[i], curr_slope), .01)
    ratio2 = max(slope[new[i][1]], curr_slope)/max(min(slope[new[i][1]], curr_slope), .01)
    if ratio<10 and ratio2<10:
        im=cv2.line(im, start, end, color, thickness)
        
    

In [120]:
cv2.imwrite('rrr4.jpg', im)

True

In [67]:
slope = np.load('slope.npy')

In [82]:
new2

[[array([394, 314], dtype=int64),
  array([394, 316], dtype=int64),
  array([441, 594], dtype=int64),
  array([439, 596], dtype=int64),
  array([445, 594], dtype=int64)],
 [array([394, 316], dtype=int64),
  array([441, 594], dtype=int64),
  array([445, 594], dtype=int64),
  array([448, 594], dtype=int64),
  array([439, 596], dtype=int64)],
 [array([394, 314], dtype=int64),
  array([441, 594], dtype=int64),
  array([445, 594], dtype=int64),
  array([448, 594], dtype=int64),
  array([439, 596], dtype=int64)],
 [array([441, 594], dtype=int64),
  array([445, 594], dtype=int64),
  array([448, 594], dtype=int64),
  array([394, 316], dtype=int64),
  array([394, 314], dtype=int64)],
 [array([439, 596], dtype=int64),
  array([445, 594], dtype=int64),
  array([448, 594], dtype=int64),
  array([394, 316], dtype=int64),
  array([394, 314], dtype=int64)],
 [array([448, 594], dtype=int64),
  array([441, 594], dtype=int64),
  array([439, 596], dtype=int64),
  array([394, 316], dtype=int64),
  array([

In [109]:
new

[[array([394, 314], dtype=int64), 1],
 [array([394, 316], dtype=int64), 2],
 [array([394, 314], dtype=int64), 1],
 [array([441, 594], dtype=int64), 4],
 [array([439, 596], dtype=int64), 3],
 [array([448, 594], dtype=int64), 6],
 [array([445, 594], dtype=int64), 5],
 [array([ 497, 5146], dtype=int64), 8],
 [array([ 497, 5144], dtype=int64), 7],
 [array([ 507, 4914], dtype=int64), 10],
 [array([ 506, 4913], dtype=int64), 9],
 [array([532, 963], dtype=int64), 12],
 [array([531, 964], dtype=int64), 11],
 [array([ 563, 1206], dtype=int64), 14],
 [array([ 562, 1205], dtype=int64), 13],
 [array([ 612, 3413], dtype=int64), 16],
 [array([ 608, 3401], dtype=int64), 15],
 [array([ 617, 2904], dtype=int64), 18],
 [array([ 618, 2902], dtype=int64), 19],
 [array([ 617, 2904], dtype=int64), 18],
 [array([ 622, 3452], dtype=int64), 22],
 [array([ 618, 2902], dtype=int64), 19],
 [array([ 619, 3448], dtype=int64), 20],
 [array([ 636, 2820], dtype=int64), 25],
 [array([ 636, 3508], dtype=int64), 26],
 [a