In [109]:
import bezier
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [110]:
img = cv2.imread('A0005-_1_.jpg',0)
img = cv2.medianBlur(img,5)
ret,image = cv2.threshold(img,127,255,cv2.THRESH_BINARY)

In [111]:
cv2.imwrite('binary.jpg', image)
image = image/255.0

In [112]:
image.shape

(3378, 5200)

In [113]:
image = 1 - image

In [114]:
from skimage.morphology import skeletonize, thin

skeleton = skeletonize(image)
thinned = thin(image)
#thinned_partial = thin(image, max_iter=25)



In [88]:
skeleton

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [140]:
thinned.shape

(3378, 5200)

In [115]:
skeleton=255-skeleton*255
thinned=255-thinned*255

In [116]:
cv2.imwrite('skeleton.jpg', skeleton)
cv2.imwrite('thinned.jpg', thinned)

True

In [156]:
mask = np.ones((3,3))

In [157]:
mask

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [119]:
ep = cv2.filter2D(skeleton/255.0, -1, mask)
ep2 = cv2.filter2D(thinned/255.0, -1, mask)

In [120]:
d=np.where(ep==7)
d2=np.where(ep2==7)

In [96]:
img1 = cv2.imread('A0005-_1_.jpg')

In [97]:
img2 = cv2.imread('skeleton.jpg')

In [98]:
img2[0][0]

array([255, 255, 255], dtype=uint8)

In [138]:
ans1=[]
for i in range(len(d[0])):
    if skeleton[d[0][i]][d[1][i]]==0:
        ans1.append([d[0][i], d[1][i]])

In [143]:
ans2=[]
for i in range(len(d2[0])):
    if thinned[d2[0][i]][d2[1][i]]==0:
        ans2.append([d2[0][i], d2[1][i]])

In [80]:
cv2.imwrite('rr.jpg', img2)

True

In [104]:
l=[]
for i in range(3378):
    for j in range(5200):
        if img2[i][j][0]==0 and img2[i][j][1]==0 and img2[i][j][2]==255:
            l.append([i,j])

In [107]:
l=np.asarray(l)

In [145]:
np.save('l2.npy', ans2)

In [124]:
len(d2[0])

33989

In [126]:
skeleton.shape

(3378, 5200)

In [141]:
len(ans1)

334

In [144]:
len(ans2)

341

In [147]:
img2 = cv2.imread('skeleton.jpg')
img3 = cv2.imread('thinned.jpg')

In [149]:
for i in range(len(ans1)):
    img2[ans1[i][0]][ans1[i][1]]=[0,0,255]

In [150]:
for i in range(len(ans2)):
    img3[ans2[i][0]][ans2[i][1]]=[0,0,255]

In [151]:
cv2.imwrite('rr.jpg', img2)
cv2.imwrite('rr2.jpg', img2)

True

In [244]:
def func(x, y, img5):
    if x!=0 and y!=0:
        if img5[x-1][y-1]==0:
            return [x-1, y-1]
    if x<3377 and y<5199:    
        if img5[x+1][y+1]==0:
            return [x+1, y+1]
    if x!=0:    
        if img5[x-1][y]==0:
            return [x-1, y]
    if x!=0 and y<5199:    
        if img5[x-1, y+1]==0:
            return [x-1, y+1]
    if y!=0:    
        if img5[x, y-1]==0:
            return [x, y-1]
    if y<5199:    
        if img5[x, y+1]==0:
            return [x, y+1]
    if x<3377 and y!=0:    
        if img5[x+1, y-1]==0:
            return [x+1, y-1]
    
    if x<3377:
        if img5[x+1, y]==0:
            return [x+1, y]

In [245]:
neighbour=[]
for i in range(len(ans1)):
    neighbour.append(func(ans1[i][0], ans1[i][1], skeleton))

In [231]:
q=func(18, 20, skeleton)

In [232]:
print(q)

[19, 19]


In [241]:
ans1[7]

[497, 5144]

In [203]:
def func2(x, y, img):
    print(img[x-1][y-1])
    print(img[x-1][y+1])
    print(img[x-1][y])
    print(img[x][y-1])
    print(img[x][y+1])
    print(img[x+1][y-1])
    print(img[x+1][y+1])
    print(img[x+1][y])
    print(img[x-1:x+2, y-1:y+2])
    

In [243]:
func2(497, 5144, skeleton)

255
255
255
255
0
255
255
255
[[255 255 255]
 [255   0   0]
 [255 255 255]]


In [209]:
func(18, 20, skeleton)
x,y=18,20

In [211]:
skeleton[x+1, y-1]

0

In [220]:
t=1
p=3
def func3():
    if t==1:
        if p==2:
            return 9
    elif t==2:
        if p==2:
            return 10
    elif t==3:
        if p==3:
            return 11
    elif t==1:
        if p==3:
            return 12
    else:
        return 13

In [221]:
func3()

In [246]:
neighbour

[[19, 19],
 [394, 315],
 [394, 315],
 [440, 595],
 [440, 595],
 [446, 594],
 [447, 594],
 [497, 5145],
 [497, 5145],
 [507, 4914],
 [506, 4913],
 [532, 963],
 [531, 964],
 [563, 1206],
 [562, 1205],
 [608, 3400],
 [612, 3414],
 [615, 2917],
 [618, 2903],
 [618, 2903],
 [619, 3447],
 [623, 2876],
 [622, 3453],
 [633, 2824],
 [633, 3500],
 [636, 2819],
 [636, 3509],
 [644, 2769],
 [651, 2730],
 [651, 2730],
 [654, 2713],
 [653, 2714],
 [657, 2698],
 [657, 2696],
 [661, 2683],
 [668, 2645],
 [672, 2628],
 [688, 2309],
 [688, 2309],
 [707, 2481],
 [722, 2403],
 [722, 2398],
 [726, 2376],
 [732, 2345],
 [736, 2329],
 [740, 1005],
 [740, 1005],
 [778, 1952],
 [820, 2856],
 [832, 2838],
 [839, 2830],
 [863, 2844],
 [869, 2841],
 [887, 3841],
 [895, 3847],
 [928, 3847],
 [935, 3851],
 [949, 3812],
 [949, 3812],
 [958, 3840],
 [976, 755],
 [976, 755],
 [991, 2197],
 [999, 2190],
 [1005, 2185],
 [1013, 2179],
 [1049, 3730],
 [1051, 3732],
 [1063, 3663],
 [1066, 2140],
 [1073, 2133],
 [1082, 3648

In [247]:
np.save('neighbour.npy', neighbour)

In [250]:
slope=[]
for i in range(len(ans1)):
    numerator=float(ans1[i][1]-neighbour[i][1])
    denominator=float(ans1[i][0]-neighbour[i][0])
    if denominator==0:
        slope.append(1000000000)
    else:
        slope.append(numerator/denominator)

In [252]:
np.save('slope.npy', slope)